# Build a test APK for Kiwi Browser

name: Build APK

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # /dev/sda1 has more available space than /dev/sdb1 (14 GB only on /dev/sdb1 at this stage)
    # so we want to take advantage of the available disk space on /dev/sda1
    steps:
      - name: Reclaiming disk space on /dev/sda1 by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Creating repository folder in /dev/sda1
        run: |
          sudo mkdir -p /repository
          sudo chown -R runner:docker /repository

      - name: Running symlink on /dev/sdb1 pointing to /dev/sda1
        run: ln -s /repository $GITHUB_WORKSPACE/repository

      - name: Gathering CIPD from cache
        id: cache-cipd
        uses: actions/cache@v1
        with:
          path: ./repository/.cipd
          key: ${{ runner.os }}-cipd

      - name: Checking-out CIPD dependencies
        uses: actions/checkout@v2
        if: steps.cache-cipd.outputs.cache-hit != 'true'
        with:
          repository: kiwibrowser/dependencies
          path: ./repository/.cipd 

      - name: Installing Python and OpenJDK
        run: sudo apt-get install python openjdk-8-jdk-headless libncurses5
    
      - name: Setting-up Java 8 as default Java provider
        run: sudo update-java-alternatives --set java-1.8.0-openjdk-amd64

      - name: Checking available disk-space
        run: df -h

      - name: Checking-out source-code
        uses: actions/checkout@v2
        with:
          path: ./repository/src 

      - name: Checking available disk-space again
        run: df -h

      - name: Verifying checkout 1
        run: ls -la

      - name: Verifying checkout 2
        run: ls -la repository

      - name: Verifying checkout 3
        run: ls -la repository/src

      - name: Installing system dependencies
        working-directory: ./repository/src
        run: |
          pwd
          sudo bash install-build-deps.sh --no-chromeos-fonts
          build/linux/sysroot_scripts/install-sysroot.py --arch=i386
          build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
          
      - name: Checking available disk-space one more time
        run: df -h

      - name: Creating output folder
        run: mkdir -p out/android_arm
      
      - name: Checking where we are
        run: pwd

