# Compile Kiwi Browser
name: automatic build of apk
#
# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Preparing storage folder
        run: |
          sudo mkdir -p /mnt/storage
          sudo chown -R runner:staff /mnt/storage
          ln -s /mnt/storage .

      - name: Checking-out source-code
        uses: actions/checkout@v2
        with:
          path: storage/src

      - name: Checking-out CIPD dependencies in $GITHUB_WORKSPACE/.cipd
        uses: actions/checkout@v2
        with:
          repository: kiwibrowser/dependencies
          path: .cipd 
          
      - name: Copying .gclient and .gclient_entries
        run: |
          cp .cipd/.gclient /mnt/storage/
          cp .cipd/.gclient_entries /mnt/storage/
          ln -s $GITHUB_WORKSPACE/.cipd /mnt/storage/

      - name: Installing system dependencies
        working-directory: /mnt/storage/src
        run: |
          sudo bash install-build-deps.sh --no-chromeos-fonts
          build/linux/sysroot_scripts/install-sysroot.py --arch=i386
          build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
          
      - name: Creating output folder
        run: mkdir -p out/android_arm
      
      - name: Generating one-time APK signature key
        run: keytool -genkey -v -keystore /mnt/storage/src/keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"

      - name: Copying args.gn to target folder
        run: cp /mnt/storage/src/.build/android_arm/args.gn out/android_arm/

      - name: Downloading depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        
      - name: Adding depot_tools to path
        run: echo "::add-path::$GITHUB_WORKSPACE/depot_tools"
      
      - name: Preparing ramdisk where the toolchains will be stored
        run: |
          sudo mkdir -p /tmp/ramdisk
          sudo mount -t tmpfs -o size=2048M tmpfs /tmp/ramdisk
          ln -s /tmp/ramdisk /mnt/storage/src/native_client/toolchain

      - name: Running gclient runhooks
        working-directory: /mnt/storage/src
        run: gclient runhooks
      
      - name: Generating build files
        working-directory: /mnt/storage/src
        run: gn gen $GITHUB_WORKSPACE/out/android_arm
      
      - name: Gathering pre-compiled objects from cache
        uses: actions/cache@v1
        with:
          path: out/android_arm
          key: ${{ runner.os }}-android_arm-obj-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android_arm-obj-

      - name: Listing files
        run: ls -la $GITHUB_WORKSPACE/out/android_arm

      - name: Listing files in obj
        run: ls -la $GITHUB_WORKSPACE/out/android_arm/obj

      - name: Compiling source-code
        working-directory: /mnt/storage/src
        run: timeout 140 ninja -C $GITHUB_WORKSPACE/out/android_arm chrome_public_apk || [ $? -eq 124 ]

     # - name: Deleting args.gn to not have it in cache
     #   run: rm -rvf out/android_arm/args.gn

     
     # - name: Uploading APK
     #   uses: actions/upload-artifact@v1
     #   with:
     #     name: apks
     #     path: out/android_arm/apks/
