# Compile Kiwi Browser
name: automatic build of apk
#
# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Installing osxfuse
        run: brew cask install osxfuse

    # Docker doesn't support MacOS natively, so we have to workaround it.
    #
    # First, using "docker-machine", we create a VM with xhyve as hypervisor.
    # This VM runs a Linux-derived OS called Boot2docker.
    #
    # Within this Boot2docker VM, we can spawn other OS (such as our Ubuntu Linux).
    # We spawn one Linux (Ubuntu) instance using the "docker" command that remotely controls the agent within Boot2docker.
    #
      - name: Installing docker
        run: brew install docker docker-compose docker-machine xhyve docker-machine-driver-xhyve
        
      - name: Setting up docker
        run: |
          sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
          sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve  
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso

      - name: Booting machine
        run: for i in $(seq 1 10); do docker-machine create --driver xhyve --xhyve-rawdisk --xhyve-cpu-count 6 --xhyve-memory-size 8000 --xhyve-disk-size '100000' default && s=0 && break || sudo kill -9 `ps aux | grep xhyve | grep -v grep | awk '{print $2}'` && sudo rm -rf /Users/runner/.docker/machine/machines/default && s=$? && sleep 15; done; (exit $s)    # Retry 10 times before abort
          
      - name: Exporting docker environment variables
        run: |
          DOCKER_TLS_VERIFY="$(docker-machine env default | grep DOCKER_TLS_VERIFY | sed -e 's/.*="//g' -e 's/"$//g')"
          DOCKER_HOST="$(docker-machine env default | grep DOCKER_HOST | sed -e 's/.*="//g' -e 's/"$//g')"
          DOCKER_CERT_PATH="$(docker-machine env default | grep DOCKER_CERT_PATH | sed -e 's/.*="//g' -e 's/"$//g')"
          DOCKER_MACHINE_NAME="$(docker-machine env default | grep DOCKER_MACHINE_NAME | sed -e 's/.*="//g' -e 's/"$//g')"
          DOCKER_IP="$(docker-machine ip default)";
          echo ::set-env name=DOCKER_TLS_VERIFY::${DOCKER_TLS_VERIFY}
          echo ::set-env name=DOCKER_HOST::${DOCKER_HOST}
          echo ::set-env name=DOCKER_CERT_PATH::${DOCKER_CERT_PATH}
          echo ::set-env name=DOCKER_MACHINE_NAME::${DOCKER_MACHINE_NAME}
          echo ::set-env name=DOCKER_IP::${DOCKER_IP}

      - name: Starting Ubuntu machine
        run: docker run --name ubuntu -t -d ubuntu:eoan
        
      - name: Checking available disk-space
        run: docker exec ubuntu df -h

      - name: Installing git inside virtual environment
        run: |
          docker exec ubuntu apt-get update
          docker exec ubuntu apt-get install -y git

      - name: Copying gitconfig into Docker instance
        run: docker cp ~/.gitconfig ubuntu:~/.gitconfig

      - name: Preparing storage folder
        run: docker exec ubuntu mkdir -p $GITHUB_WORKSPACE/storage
 
      - name: Creating tools to route checkout inside docker
        run: |
          mkdir -p tools
          echo '#!/bin/sh' > tools/git
          echo 'docker exec ubuntu mkdir -p $PWD/.git' >> tools/git
          echo 'if [ "$1" != "submodule_ignored" -a "$1" != "config_ignored" ]' >> tools/git
          echo 'then' >> tools/git
          echo '  docker exec -w $PWD ubuntu git $*' >> tools/git
          echo 'fi' >> tools/git
          echo 'exit $?' >> tools/git
          chmod +x tools/git
          echo '#!/bin/sh' > tools/tar
          echo 'docker exec ubuntu mkdir -p $PWD' >> tools/tar
          echo 'docker exec -w $PWD ubuntu tar $*' >> tools/tar
          echo 'exit $?' >> tools/tar
          chmod +x tools/tar
      
      - name: Re-routing git commands inside docker
        run: echo "::add-path::$GITHUB_WORKSPACE/tools"

      - name: Checking-out source-code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          path: storage/src

      - name: Checking-out CIPD dependencies in $GITHUB_WORKSPACE/.cipd
        uses: actions/checkout@v2
        with:
          repository: kiwibrowser/dependencies
          path: .cipd

      - name: Checking storage directory
        run: ls -la .cipd
        
      - name: Copying .gclient and .gclient_entries
        run: |
          cp $GITHUB_WORKSPACE/.cipd/.gclient $GITHUB_WORKSPACE/storage/
          cp $GITHUB_WORKSPACE/.cipd/.gclient_entries $GITHUB_WORKSPACE/storage/
          ln -s $GITHUB_WORKSPACE/.cipd $GITHUB_WORKSPACE/storage/

      - name: Creating output folder
        run: mkdir -p out/android_arm
      
      - name: Generating one-time APK signature key
        run: keytool -genkey -v -keystore $GITHUB_WORKSPACE/storage/src/keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"

      - name: Copying args.gn to target folder
        run: cp $GITHUB_WORKSPACE/storage/src/.build/android_arm/args.gn out/android_arm/

      - name: Downloading depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        
      - name: Adding depot_tools to path
        run: echo "::add-path::$GITHUB_WORKSPACE/depot_tools"

      - name: Running gclient runhooks
        working-directory: /Users/runner/storage/src
        run: gclient runhooks

      - name: Removing files
        run: |
          rm -rf /Users/runner/storage/src/third_party/llvm-build/Release+Asserts/bin/llvm-ar
#          mkdir -p /Users/runner/storage/src/third_party/llvm-build/Release+Asserts

      - name: Listing files
        run: ls -la /Users/runner/storage/src/third_party/llvm-build/

      - name: Listing files
        run: ls -la /Users/runner/storage/src/third_party/llvm-build/Release+Asserts/bin
              
      - name: Generating build files
        working-directory: /Users/runner/storage/src
        run: gn gen $GITHUB_WORKSPACE/out/android_arm
      
      - name: Gathering pre-compiled objects from cache
        uses: actions/cache@v1
        with:
          path: out/android_arm
          key: ${{ runner.os }}-android_arm-obj-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android_arm-obj-

      - name: Compiling source-code
        working-directory: /Users/runner/storage/src
        run: ninja -C $GITHUB_WORKSPACE/out/android_arm chrome_public_apk

      - name: Deleting args.gn to not have it in cache
        run: rm -rvf out/android_arm/args.gn

      - name: Uploading APK
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: out/android_arm/apks/
